version: "3.7"

services:
  app:
    build:
      context: .
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=qwerty
      - PORT=5000
      - HOST=0.0.0.0
      - DB_HOST=db
      - DB_PORT=27017
    restart: on-failure
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      node app.js
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=qwerty
    ports:
      - "27018:27017"
    restart: on-failure
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
